import pandas as pd
import pytest

from wc2026_model.data.international_results import standardize_international_results


@pytest.fixture
def sample_international_results() -> pd.DataFrame:
    raw = pd.DataFrame(
        [
            {
                "date": "2024-01-01",
                "home_team": "Alpha",
                "away_team": "Beta",
                "home_score": 2,
                "away_score": 0,
                "tournament": "Friendly",
                "city": "A",
                "country": "Alpha",
                "neutral": False,
            },
            {
                "date": "2024-01-05",
                "home_team": "Gamma",
                "away_team": "Delta",
                "home_score": 1,
                "away_score": 0,
                "tournament": "Friendly",
                "city": "G",
                "country": "Gamma",
                "neutral": False,
            },
            {
                "date": "2024-01-10",
                "home_team": "Alpha",
                "away_team": "Gamma",
                "home_score": 3,
                "away_score": 1,
                "tournament": "FIFA World Cup qualification",
                "city": "A",
                "country": "Alpha",
                "neutral": False,
            },
            {
                "date": "2024-01-15",
                "home_team": "Beta",
                "away_team": "Delta",
                "home_score": 1,
                "away_score": 1,
                "tournament": "Friendly",
                "city": "B",
                "country": "Beta",
                "neutral": False,
            },
            {
                "date": "2024-01-20",
                "home_team": "Alpha",
                "away_team": "Delta",
                "home_score": 2,
                "away_score": 1,
                "tournament": "FIFA World Cup qualification",
                "city": "A",
                "country": "Alpha",
                "neutral": False,
            },
            {
                "date": "2024-01-25",
                "home_team": "Beta",
                "away_team": "Gamma",
                "home_score": 0,
                "away_score": 2,
                "tournament": "Friendly",
                "city": "B",
                "country": "Beta",
                "neutral": False,
            },
            {
                "date": "2024-02-01",
                "home_team": "Delta",
                "away_team": "Alpha",
                "home_score": 0,
                "away_score": 1,
                "tournament": "Friendly",
                "city": "D",
                "country": "Delta",
                "neutral": False,
            },
            {
                "date": "2024-02-05",
                "home_team": "Gamma",
                "away_team": "Beta",
                "home_score": 2,
                "away_score": 0,
                "tournament": "Friendly",
                "city": "G",
                "country": "Gamma",
                "neutral": False,
            },
            {
                "date": "2024-02-10",
                "home_team": "Delta",
                "away_team": "Gamma",
                "home_score": 1,
                "away_score": 2,
                "tournament": "Friendly",
                "city": "D",
                "country": "Delta",
                "neutral": False,
            },
            {
                "date": "2024-02-15",
                "home_team": "Beta",
                "away_team": "Alpha",
                "home_score": 1,
                "away_score": 2,
                "tournament": "FIFA World Cup qualification",
                "city": "B",
                "country": "Beta",
                "neutral": False,
            },
            {
                "date": "2024-02-20",
                "home_team": "Delta",
                "away_team": "Beta",
                "home_score": 1,
                "away_score": 0,
                "tournament": "Friendly",
                "city": "D",
                "country": "Delta",
                "neutral": False,
            },
            {
                "date": "2024-02-25",
                "home_team": "Gamma",
                "away_team": "Alpha",
                "home_score": 1,
                "away_score": 1,
                "tournament": "FIFA World Cup qualification",
                "city": "Neutral",
                "country": "Portugal",
                "neutral": True,
            },
        ]
    )
    return standardize_international_results(raw)
